### ISSUE TITLE
Add a demo/sample project

### ISSUE THREAD

**Issue by VashJuan** [eraware/dnn-elements#352]
[enhancement request]
For folks (like me) trying to understand a new project and see the effect, it would be nice to at least have screen shots of these components to get a feel for what the base UI/appearance is.

Ideally there would be a sample/test application to see/exercise all these components with a minimum of effort for lazy folks (like me) browsing around. 

I understand having a running demo might require hosting fees, but maybe you could have a demo (or one for each component?) run on https://www.typescriptlang.org/play or one of the similar online environments.

Love this idea for sure. I may even try to add some of my own?!

**Comment by valadas** [comment]
The samples/tests are in the HTML file right here https://github.com/eraware/dnn-elements/blob/development/src/index.html

Basically, if you just do an `npm run start` you will get that served.

But I guess I could publish a demo as a github page, that would be nice for sure

**Comment by VashJuan** [comment]
If I download and view the image in Firefox I get the following - not great. Maybe I need to build it or use Chrome, but at this point a screenshot would have been easier for some folk?

![image](https://user-images.githubusercontent.com/8594671/126079234-e707fa37-2dfd-4ad5-9d7b-457c8c3c1be0.png)

**Comment by VashJuan** [comment]
Oh, sorry, I just read "npm run start" which worked fine - once I downloaded the whole project. Maybe just add the following screenshot to the main readme.md page? That would suffice for my use case!

![image](https://user-images.githubusercontent.com/8594671/126079414-dcfd186f-59ec-41cf-a38e-769d87f99280.png)

**Comment by valadas** [comment]
I gonna reopen because it would be cool to have a demo without download
